#!/usr/bin/env python3
import subprocess
import sys

def run_gitleaks():
    try:
        subprocess.run(['gitleaks', '--path', '.'], check=True)
    except subprocess.CalledProcessError:
        print("Error: Secrets detected in the code. Commit rejected.")
        sys.exit(1)

def main():
    run_gitleaks()

if __name__ == '__main__':
    main()
